language: ruby

rvm:
- 2.1.0
branches:
  except:
  - production-build
  - "/^v\\d+$/"
before_install:
- psql -c 'create database ember_cli_app_test;' -U postgres
- npm install -g ember-cli
- npm install -g bower
- echo 'y' | ember
install:
- gem install sass
- gem install compass
- cp rails/config/database.yml.travis rails/config/database.yml
- cd rails && bundle install --without development --deployment && RAILS_ENV=test bundle exec rake db:migrate && cd ..
before_script:
- cd ember && npm install && bower install && ember build development && mv dist ../rails/public/assets/ && cd ..
script:
- cd rails && bundle exec rake
addons:
  postgresql: '9.3'
